import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('pageerror', (e) => console.log('pageerror', e.message));
p.on('console', (m) => { if (m.type()==='error'||m.type()==='warning') console.log(m.type(), m.text()); });
await p.goto('http://127.0.0.1:5173/');
await p.waitForFunction(() => !!window.__PALIMPSEST__, null, { timeout: 60000 });
await p.evaluate(() => { __PALIMPSEST__.setQuality('low'); });
await p.click('#btn-start');
await p.evaluate(() => { __PALIMPSEST__.advanceTicks(60*31); __PALIMPSEST__.settle(1.5); });
const o = await p.evaluate(() => __PALIMPSEST__.offerScreen(0));
const s = await p.evaluate(() => __PALIMPSEST__.socketScreen(4));
console.log('offer', o, 'socket', s);
await p.mouse.move(o.x, o.y);
await p.mouse.down();
for (let i = 1; i <= 8; i++) await p.mouse.move(o.x + (s.x - o.x) * i / 8, o.y + (s.y - o.y) * i / 8);
await p.screenshot({ path: 'tools/out/drag-mid.png' });
await p.mouse.up();
await p.evaluate(() => __PALIMPSEST__.settle(0.6));
console.log(JSON.stringify((await p.evaluate(() => __PALIMPSEST__.snapshot())).slots.map(x=>x&&x.defId)), JSON.stringify((await p.evaluate(() => __PALIMPSEST__.snapshot())).draft.stage));
await p.screenshot({ path: 'tools/out/drag-after.png' });
await b.close();
