import { chromium } from 'playwright';
const b = await chromium.launch({ args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 720 } });
p.on('pageerror', (e) => console.log('pageerror', e.message));
p.on('console', (m) => { if (m.type()==='error'||m.type()==='warning') console.log(m.type(), m.text()); });
await p.goto('http://127.0.0.1:5173/');
await p.waitForFunction(() => !!window.__PALIMPSEST__, null, { timeout: 60000 });
await p.click('#btn-start');
await p.evaluate(() => __PALIMPSEST__.settle(1.5));
const s = await p.evaluate(() => __PALIMPSEST__.snapshot());
const tower = s.hand.find((c) => c.defId === 'needle');
// hover near the bottom to raise the hand
await p.mouse.move(640, 690);
await p.evaluate(() => __PALIMPSEST__.settle(0.8));
await p.screenshot({ path: 'tools/out/v2-hand-raised.png', timeout: 180000 });
const from = await p.evaluate((u) => __PALIMPSEST__.handCardScreen(u), tower.uid);
const to = await p.evaluate(() => __PALIMPSEST__.socketScreen(1));
console.log('from', from, 'to', to);
await p.mouse.move(from.x, from.y); await p.mouse.down();
for (let i = 1; i <= 10; i++) await p.mouse.move(from.x + (to.x-from.x)*i/10, from.y + (to.y-from.y)*i/10);
await p.evaluate(() => __PALIMPSEST__.settle(0.2));
await p.screenshot({ path: 'tools/out/v2-drag.png', timeout: 180000 });
await p.mouse.up();
await p.evaluate(() => __PALIMPSEST__.settle(1));
const s2 = await p.evaluate(() => __PALIMPSEST__.snapshot());
console.log('slots', JSON.stringify(s2.slots.map(x=>x&&x.defId)), 'energy', s2.turn.energy);
const f1 = await p.evaluate(() => __PALIMPSEST__.frustum());
await p.click('#btn-end-turn');
await p.evaluate(() => { __PALIMPSEST__.advanceTicks(60*22); __PALIMPSEST__.settle(0.5); });
const f2 = await p.evaluate(() => __PALIMPSEST__.frustum());
console.log('frustum same', JSON.stringify(f1) === JSON.stringify(f2));
const nc = await p.evaluate(() => __PALIMPSEST__.snapshot().enemies.length);
console.log('enemies', nc);
const cs = await p.evaluate(() => __PALIMPSEST__.cardScreen(1));
await p.mouse.move(cs.x, cs.y);
await p.evaluate(() => __PALIMPSEST__.settle(0.5));
await p.screenshot({ path: 'tools/out/v2-combat.png', timeout: 180000 });
await b.close();
